export const POLOS_SISTEMA = [
  { codigo:"1822", nome:"JAIR ANT - MONTEIRO E BARBOSA SERVICOS EDUCACIONAIS", cidade:"", estado:"" },
  { codigo:"1911", nome:"PAULO PIMENTEL E PIMENTEL 00846877201", cidade:"", estado:"" },
  { codigo:"1866", nome:"19888793 Rosana Aparecida Pires Menezes", cidade:"", estado:"" },
  { codigo:"1703", nome:"43.619.313 DANIELE ECCARD MOUTA", cidade:"", estado:"" },
  { codigo:"1583", nome:"44.809.190 WANDER MARINHO FERREIRA", cidade:"", estado:"" },
  { codigo:"1574", nome:"49.275.722 ANDREA VAZ GONCALVES", cidade:"", estado:"" },
  { codigo:"554",  nome:"49.528.877 SAVIO VICENTE CHAIA", cidade:"", estado:"" },
  { codigo:"561",  nome:"51.172.804 GUILLERMO JAVIER CADENASSO NAV", cidade:"", estado:"" },
  { codigo:"1641", nome:"52.676.538 LUCAS LEANDRO PANTOJA DOS SANT", cidade:"", estado:"" },
  { codigo:"1879", nome:"57.322.493 CRISTIANE PEREIRA MACHADO", cidade:"", estado:"" },
  { codigo:"1885", nome:"61.355.248 WESLEY ALVES DA SILVA", cidade:"", estado:"" },
  { codigo:"1994", nome:"65.926.502 CINTIA GOMES TORALLES", cidade:"", estado:"" },
  { codigo:"1919", nome:"A+ ACADEMY EDUCACAO LTDA", cidade:"", estado:"" },
  { codigo:"1725", nome:"Maceió (Tabuleiro do Martins)", cidade:"Maceió", estado:"AL" },
  { codigo:"1989", nome:"Benjamin Constant (Centro)", cidade:"Benjamin Constant", estado:"AM" },
  { codigo:"1969", nome:"Coari (ESPIRITO SANTO)", cidade:"Coari", estado:"AM" },
  { codigo:"518",  nome:"Iranduba (Alto)", cidade:"Iranduba", estado:"AM" },
  { codigo:"1874", nome:"Manaus (Gilberto Mestrinho)", cidade:"Manaus", estado:"AM" },
  { codigo:"1806", nome:"Manaus (Japiim)", cidade:"Manaus", estado:"AM" },
  { codigo:"1837", nome:"Novo Aripuanã (CENTRO)", cidade:"Novo Aripuanã", estado:"AM" },
  { codigo:"383",  nome:"São Paulo de Olivença (Bonfim)", cidade:"São Paulo de Olivença", estado:"AM" },
  { codigo:"1968", nome:"Tefé (Juruá)", cidade:"Tefé", estado:"AM" },
  { codigo:"1777", nome:"ASSOCIACAO DOS PROFESSORES DE OSASCO - AP", cidade:"Osasco", estado:"SP" },
  { codigo:"1864", nome:"Avant Centro Profissionalizante Ltda", cidade:"", estado:"" },
  { codigo:"1995", nome:"Alagoinhas (Centro)", cidade:"Alagoinhas", estado:"BA" },
  { codigo:"155",  nome:"Dias D'Ávila (Dias D'ávila)", cidade:"Dias D'Ávila", estado:"BA" },
  { codigo:"169",  nome:"Filadélfia (Centro)", cidade:"Filadélfia", estado:"BA" },
  { codigo:"1955", nome:"Formosa do Rio Preto (JARDIM IMPERIAL)", cidade:"Formosa do Rio Preto", estado:"BA" },
  { codigo:"347",  nome:"Itaberaba (Alto da Boa Vista)", cidade:"Itaberaba", estado:"BA" },
  { codigo:"345",  nome:"Lage dos Negros (Centro)", cidade:"Lage dos Negros", estado:"BA" },
  { codigo:"114",  nome:"Lauro de Freitas (Itinga)", cidade:"Lauro de Freitas", estado:"BA" },
  { codigo:"1881", nome:"Milagres (CENTRO)", cidade:"Milagres", estado:"BA" },
  { codigo:"57",   nome:"Palmeiras (Centro)", cidade:"Palmeiras", estado:"BA" },
  { codigo:"1600", nome:"Porto Seguro (Centro)", cidade:"Porto Seguro", estado:"BA" },
  { codigo:"131",  nome:"Salvador (Campo da Pólvora)", cidade:"Salvador", estado:"BA" },
  { codigo:"1903", nome:"Salvador (Pituba)", cidade:"Salvador", estado:"BA" },
  { codigo:"2001", nome:"Salvador (Rio Vermelho)", cidade:"Salvador", estado:"BA" },
  { codigo:"1962", nome:"Santo Estevão (Centro)", cidade:"Santo Estevão", estado:"BA" },
  { codigo:"249",  nome:"Simões Filho (Centro)", cidade:"Simões Filho", estado:"BA" },
  { codigo:"353",  nome:"TEODORO SAMPAIO (Centro)", cidade:"Teodoro Sampaio", estado:"BA" },
  { codigo:"103",  nome:"Umburanas (Centro)", cidade:"Umburanas", estado:"BA" },
  { codigo:"1565", nome:"C. R. BRANDALISE LTDA", cidade:"", estado:"" },
  { codigo:"373",  nome:"Crato (Seminário)", cidade:"Crato", estado:"CE" },
  { codigo:"1851", nome:"Fortaleza (Cidade dos Funcionários)", cidade:"Fortaleza", estado:"CE" },
  { codigo:"1909", nome:"Milhã (PADRE CICERO)", cidade:"Milhã", estado:"CE" },
  { codigo:"326",  nome:"Sobral (Jocely Dantas)", cidade:"Sobral", estado:"CE" },
  { codigo:"1812", nome:"CEMS CENTRO EDUCACIONAL DE MATO GROSSO DO SUL", cidade:"", estado:"MS" },
  { codigo:"1926", nome:"CENTRO PRIME DE ENSINO E DESENVOLVIMENTO", cidade:"", estado:"" },
  { codigo:"1618", nome:"CT CURSOS E TREINAMENTOS", cidade:"", estado:"" },
  { codigo:"1742", nome:"Brasília (Asa Norte)", cidade:"Brasília", estado:"DF" },
  { codigo:"340",  nome:"Brasília (Engenho Velho)", cidade:"Brasília", estado:"DF" },
  { codigo:"1892", nome:"Brasília (Paranoá)", cidade:"Brasília", estado:"DF" },
  { codigo:"497",  nome:"Brasília (Taguatinga Centro)", cidade:"Brasília", estado:"DF" },
  { codigo:"1779", nome:"Brasília (Taguatinga Norte)", cidade:"Brasília", estado:"DF" },
  { codigo:"1804", nome:"EDUCASIM - CENTRO DE FORMAÇÃO EDUCACIONAL", cidade:"", estado:"" },
  { codigo:"1813", nome:"EDUHUB LTDA.", cidade:"", estado:"" },
  { codigo:"1640", nome:"Aracruz (Segato)", cidade:"Aracruz", estado:"ES" },
  { codigo:"1745", nome:"Cachoeiro de Itapemirim (Centro)", cidade:"Cachoeiro de Itapemirim", estado:"ES" },
  { codigo:"1714", nome:"Cachoeiro de Itapemirim (Lauro Viana)", cidade:"Cachoeiro de Itapemirim", estado:"ES" },
  { codigo:"1964", nome:"Vila Velha (Glória)", cidade:"Vila Velha", estado:"ES" },
  { codigo:"1895", nome:"Escola de Qualificação Profissional Grupo", cidade:"", estado:"" },
  { codigo:"1890", nome:"Ezequiel B. Marques e Cia LTDA", cidade:"", estado:"" },
  { codigo:"1857", nome:"FABRICIO OLIVEIRA PACHECO", cidade:"", estado:"" },
  { codigo:"521",  nome:"FACULDADE SANTINO ESCOLA SUPERIOR DE GRAD", cidade:"", estado:"" },
  { codigo:"15",   nome:"FECAF - Polo Americas", cidade:"São Paulo", estado:"SP" },
  { codigo:"1844", nome:"FUTURO CENTRO EDUCACIONAL LTDA", cidade:"", estado:"" },
  { codigo:"1876", nome:"GC Educacional Ltda", cidade:"", estado:"" },
  { codigo:"1815", nome:"Alexânia (Nova Flórida)", cidade:"Alexânia", estado:"GO" },
  { codigo:"562",  nome:"Anápolis (Centro)", cidade:"Anápolis", estado:"GO" },
  { codigo:"1761", nome:"Aparecida de Goiânia (Vila Oliveira)", cidade:"Aparecida de Goiânia", estado:"GO" },
  { codigo:"1726", nome:"Catalão (Setor Central)", cidade:"Catalão", estado:"GO" },
  { codigo:"292",  nome:"Goiânia (Setor Bueno)", cidade:"Goiânia", estado:"GO" },
  { codigo:"402",  nome:"Goiânia (Jardim América)", cidade:"Goiânia", estado:"GO" },
  { codigo:"467",  nome:"Goiânia (Jardim Balneário Meia Ponte)", cidade:"Goiânia", estado:"GO" },
  { codigo:"421",  nome:"Inhumas (Centro)", cidade:"Inhumas", estado:"GO" },
  { codigo:"1678", nome:"Ipameri (Centro)", cidade:"Ipameri", estado:"GO" },
  { codigo:"1748", nome:"Morrinhos (Jardim Venezuela)", cidade:"Morrinhos", estado:"GO" },
  { codigo:"1907", nome:"Nerópolis (Centro)", cidade:"Nerópolis", estado:"GO" },
  { codigo:"1695", nome:"Planaltina (Setor Leste)", cidade:"Planaltina", estado:"GO" },
  { codigo:"528",  nome:"Valparaíso de Goiás (Valparaiso I)", cidade:"Valparaíso de Goiás", estado:"GO" },
  { codigo:"486",  nome:"Águas Lindas de Goiás (Jardim da Barragem II)", cidade:"Águas Lindas de Goiás", estado:"GO" },
  { codigo:"1576", nome:"Gabriel Alves de Lima Santos", cidade:"", estado:"" },
  { codigo:"1642", nome:"Gabriel Rocha e Silva", cidade:"", estado:"" },
  { codigo:"1867", nome:"IGM CURSOS E TREINAMENTOS LDTA", cidade:"", estado:"" },
  { codigo:"1854", nome:"INSPIRAÇÃO INFORMATICA LTDA ME", cidade:"", estado:"" },
  { codigo:"1848", nome:"INSTITUIÇÃO DE ENSINO RAMOS LTDA", cidade:"", estado:"" },
  { codigo:"1902", nome:"INSTITUTO DE EDUCAÇÃO PROFISSIONAL E POLI", cidade:"", estado:"" },
  { codigo:"1855", nome:"INSTITUTO MARQUES LTDA", cidade:"", estado:"" },
  { codigo:"1856", nome:"Instituto Axie de Ensino Ltda", cidade:"", estado:"" },
  { codigo:"1896", nome:"Irenas Instituto Renascer de Educação For", cidade:"", estado:"" },
  { codigo:"1604", nome:"JHORDY BRENO ALMEIDA DOS SANTOS", cidade:"", estado:"" },
  { codigo:"555",  nome:"JOHNNY WILLIAN BUSSOLARO", cidade:"", estado:"" },
  { codigo:"1821", nome:"JONATHAN OLIVEIRA CARVALHO ME", cidade:"", estado:"" },
  { codigo:"1820", nome:"Jonas Rodrigues dos Santos", cidade:"", estado:"" },
  { codigo:"1849", nome:"M. J. UHDE E UHDE LTDA", cidade:"", estado:"" },
  { codigo:"524",  nome:"Santa Inês (Nova Santa Inês)", cidade:"Santa Inês", estado:"MA" },
  { codigo:"1859", nome:"São Luís (Outeiro da Cruz)", cidade:"São Luís", estado:"MA" },
  { codigo:"1870", nome:"MAGALHAES EDUCAÇÃO BREU BRANCO LTDA", cidade:"Breu Branco", estado:"PA" },
  { codigo:"1917", nome:"MAGALHAES EDUCAÇÃO BREU BRANCO LTDA 2", cidade:"Breu Branco", estado:"PA" },
  { codigo:"380",  nome:"Arantina (Centro)", cidade:"Arantina", estado:"MG" },
  { codigo:"98",   nome:"Barbacena (Centro)", cidade:"Barbacena", estado:"MG" },
  { codigo:"132",  nome:"Belo Horizonte (Centro)", cidade:"Belo Horizonte", estado:"MG" },
  { codigo:"1635", nome:"Belo Horizonte (Floresta)", cidade:"Belo Horizonte", estado:"MG" },
  { codigo:"1707", nome:"Belo Horizonte (Milionários - Barreiro)", cidade:"Belo Horizonte", estado:"MG" },
  { codigo:"1932", nome:"Belo Horizonte (REDE AVANTE)", cidade:"Belo Horizonte", estado:"MG" },
  { codigo:"1570", nome:"Belo Horizonte (Venda Nova)", cidade:"Belo Horizonte", estado:"MG" },
  { codigo:"1949", nome:"Betim (Vila Cristina)", cidade:"Betim", estado:"MG" },
  { codigo:"466",  nome:"Bom Despacho (São João)", cidade:"Bom Despacho", estado:"MG" },
  { codigo:"1811", nome:"Divinópolis (Centro)", cidade:"Divinópolis", estado:"MG" },
  { codigo:"406",  nome:"Governador Valadares (Centro)", cidade:"Governador Valadares", estado:"MG" },
  { codigo:"1945", nome:"Guaxupé (Centro)", cidade:"Guaxupé", estado:"MG" },
  { codigo:"1788", nome:"Ipatinga (Caravelas)", cidade:"Ipatinga", estado:"MG" },
  { codigo:"1769", nome:"Itaúna (Nogueira Machado)", cidade:"Itaúna", estado:"MG" },
  { codigo:"236",  nome:"João Monlevade (Carneirinhos)", cidade:"João Monlevade", estado:"MG" },
  { codigo:"164",  nome:"Juiz de Fora (Centro - Av. dos Andradas)", cidade:"Juiz de Fora", estado:"MG" },
  { codigo:"274",  nome:"Juiz de Fora (Centro)", cidade:"Juiz de Fora", estado:"MG" },
  { codigo:"468",  nome:"Lavras (Centro)", cidade:"Lavras", estado:"MG" },
  { codigo:"1958", nome:"Montes Claros (Centro)", cidade:"Montes Claros", estado:"MG" },
  { codigo:"201",  nome:"Ponte Nova (Guarapiranga)", cidade:"Ponte Nova", estado:"MG" },
  { codigo:"1634", nome:"Pouso Alegre (Centro)", cidade:"Pouso Alegre", estado:"MG" },
  { codigo:"1980", nome:"Ribeirão das Neves (Veneza)", cidade:"Ribeirão das Neves", estado:"MG" },
  { codigo:"163",  nome:"São Gonçalo do Sapucaí", cidade:"São Gonçalo do Sapucaí", estado:"MG" },
  { codigo:"115",  nome:"São João Del Rei (Fábricas)", cidade:"São João Del Rei", estado:"MG" },
  { codigo:"248",  nome:"São Sebastião do Paraíso (Centro)", cidade:"São Sebastião do Paraíso", estado:"MG" },
  { codigo:"1981", nome:"Uberlândia (Saraiva)", cidade:"Uberlândia", estado:"MG" },
  { codigo:"491",  nome:"Amambaí (vila fioramonte)", cidade:"Amambaí", estado:"MS" },
  { codigo:"1762", nome:"Bodoquena (CENTRO)", cidade:"Bodoquena", estado:"MS" },
  { codigo:"1947", nome:"Campo Grande (Centro)", cidade:"Campo Grande", estado:"MS" },
  { codigo:"310",  nome:"Ponta Porã (Centro)", cidade:"Ponta Porã", estado:"MS" },
  { codigo:"1737", nome:"Água Clara (AGUA CLARA)", cidade:"Água Clara", estado:"MS" },
  { codigo:"1948", nome:"Cuiabá (Centro)", cidade:"Cuiabá", estado:"MT" },
  { codigo:"1858", nome:"Cuiabá (Morada da Serra)", cidade:"Cuiabá", estado:"MT" },
  { codigo:"289",  nome:"Gaúcha do Norte (Centro)", cidade:"Gaúcha do Norte", estado:"MT" },
  { codigo:"529",  nome:"Lucas do Rio Verde (Alvorada)", cidade:"Lucas do Rio Verde", estado:"MT" },
  { codigo:"313",  nome:"Nova Marilândia (Jardim Planalto)", cidade:"Nova Marilândia", estado:"MT" },
  { codigo:"1668", nome:"Nova Mutum (Lírios do Campo)", cidade:"Nova Mutum", estado:"MT" },
  { codigo:"288",  nome:"Rondonópolis (Jardim Atlântico)", cidade:"Rondonópolis", estado:"MT" },
  { codigo:"1664", nome:"Sapezal (Cidezal l)", cidade:"Sapezal", estado:"MT" },
  { codigo:"1674", nome:"Sinop (Setor Comercial)", cidade:"Sinop", estado:"MT" },
  { codigo:"1886", nome:"Sorriso (Centro-Sul)", cidade:"Sorriso", estado:"MT" },
  { codigo:"1944", nome:"Tangará da Serra (Centro)", cidade:"Tangará da Serra", estado:"MT" },
  { codigo:"299",  nome:"Várzea Grande (Costa Verde)", cidade:"Várzea Grande", estado:"MT" },
  { codigo:"542",  nome:"Marina Aldaves Publicidade", cidade:"", estado:"" },
  { codigo:"1590", nome:"NESTI INTELIGÊNCIA EDUCACIONAL", cidade:"", estado:"" },
  { codigo:"1579", nome:"Alenquer (Luanda)", cidade:"Alenquer", estado:"PA" },
  { codigo:"1931", nome:"Belém (Coqueiro)", cidade:"Belém", estado:"PA" },
  { codigo:"1951", nome:"Belém (Marco)", cidade:"Belém", estado:"PA" },
  { codigo:"1708", nome:"Itaituba (Bela Vista)", cidade:"Itaituba", estado:"PA" },
  { codigo:"1697", nome:"Moju (Parolândia 2)", cidade:"Moju", estado:"PA" },
  { codigo:"1873", nome:"Monte Alegre (CIDADE ALTA)", cidade:"Monte Alegre", estado:"PA" },
  { codigo:"1914", nome:"Oriximiná (São Pedro)", cidade:"Oriximiná", estado:"PA" },
  { codigo:"1845", nome:"Redenção (Setor Oeste)", cidade:"Redenção", estado:"PA" },
  { codigo:"1938", nome:"Santarém (Fátima)", cidade:"Santarém", estado:"PA" },
  { codigo:"401",  nome:"Santarém (Livramento)", cidade:"Santarém", estado:"PA" },
  { codigo:"1928", nome:"PAULO CEZAR NEVES", cidade:"", estado:"" },
  { codigo:"1852", nome:"Cajazeiras (CENTRO)", cidade:"Cajazeiras", estado:"PB" },
  { codigo:"1954", nome:"Itaporanga (Loteamento Paulus)", cidade:"Itaporanga", estado:"PB" },
  { codigo:"1853", nome:"João Pessoa (Mangabeira)", cidade:"João Pessoa", estado:"PB" },
  { codigo:"1935", nome:"João Pessoa (Tambauzinho)", cidade:"João Pessoa", estado:"PB" },
  { codigo:"1941", nome:"Piancó (OURO BRANCO)", cidade:"Piancó", estado:"PB" },
  { codigo:"1952", nome:"Sousa (Centro)", cidade:"Sousa", estado:"PB" },
  { codigo:"1657", nome:"PC CONNECT TELECOM LTDA", cidade:"", estado:"" },
  { codigo:"1961", nome:"Afogados da Ingazeira (Centro)", cidade:"Afogados da Ingazeira", estado:"PE" },
  { codigo:"1966", nome:"Petrolina (Gercino Coelho)", cidade:"Petrolina", estado:"PE" },
  { codigo:"1817", nome:"POLO SÃO - Instituto Synertch LTDA", cidade:"", estado:"" },
  { codigo:"256",  nome:"Ampére (Centro)", cidade:"Ampére", estado:"PR" },
  { codigo:"1887", nome:"CORONEL DOMINGOS SOARES (Centro)", cidade:"Coronel Domingos Soares", estado:"PR" },
  { codigo:"217",  nome:"Curitiba (Boa Vista)", cidade:"Curitiba", estado:"PR" },
  { codigo:"424",  nome:"Foz do Iguaçu (Lancaster)", cidade:"Foz do Iguaçu", estado:"PR" },
  { codigo:"1805", nome:"Francisco Beltrão (Vila Nova)", cidade:"Francisco Beltrão", estado:"PR" },
  { codigo:"295",  nome:"Guarapuava (Centro)", cidade:"Guarapuava", estado:"PR" },
  { codigo:"315",  nome:"Pinhais (Weissópolis)", cidade:"Pinhais", estado:"PR" },
  { codigo:"120",  nome:"São Mateus do Sul (Centro)", cidade:"São Mateus do Sul", estado:"PR" },
  { codigo:"357",  nome:"Toledo (Centro)", cidade:"Toledo", estado:"PR" },
  { codigo:"1868", nome:"Q.I CENTRO DE ENSINO", cidade:"", estado:"" },
  { codigo:"1824", nome:"RHVS CONSULTORIA E SERVIÇOS LTDA", cidade:"", estado:"" },
  { codigo:"1721", nome:"RICCELLE OLIVEIRA DOS REIS", cidade:"", estado:"" },
  { codigo:"279",  nome:"Barra do Piraí (Centro)", cidade:"Barra do Piraí", estado:"RJ" },
  { codigo:"202",  nome:"Bom Jesus do Itabapoana (Centro)", cidade:"Bom Jesus do Itabapoana", estado:"RJ" },
  { codigo:"139",  nome:"Cabo Frio (Centro)", cidade:"Cabo Frio", estado:"RJ" },
  { codigo:"124",  nome:"Campos dos Goytacazes (Centro)", cidade:"Campos dos Goytacazes", estado:"RJ" },
  { codigo:"192",  nome:"Cantagalo (Centro)", cidade:"Cantagalo", estado:"RJ" },
  { codigo:"184",  nome:"Comendador Levy Gasparian (Centro)", cidade:"Comendador Levy Gasparian", estado:"RJ" },
  { codigo:"191",  nome:"Duque de Caxias (GRADUS ENSINO A DISTANCIA)", cidade:"Duque de Caxias", estado:"RJ" },
  { codigo:"1823", nome:"Duque de Caxias (Centro)", cidade:"Duque de Caxias", estado:"RJ" },
  { codigo:"145",  nome:"Macaé (São José do Barreto)", cidade:"Macaé", estado:"RJ" },
  { codigo:"190",  nome:"Magé (Piabetá Inhomirim)", cidade:"Magé", estado:"RJ" },
  { codigo:"183",  nome:"Niterói (Centro)", cidade:"Niterói", estado:"RJ" },
  { codigo:"188",  nome:"Nova Friburgo (Centro)", cidade:"Nova Friburgo", estado:"RJ" },
  { codigo:"1782", nome:"Nova Iguaçu (Centro Nilo Peçanha)", cidade:"Nova Iguaçu", estado:"RJ" },
  { codigo:"1923", nome:"Paraíba do Sul (Centro)", cidade:"Paraíba do Sul", estado:"RJ" },
  { codigo:"189",  nome:"Petrópolis (Centro)", cidade:"Petrópolis", estado:"RJ" },
  { codigo:"170",  nome:"Rio das Ostras (Cidade Beira Mar)", cidade:"Rio das Ostras", estado:"RJ" },
  { codigo:"496",  nome:"Rio de Janeiro (Bangu)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1982", nome:"Rio de Janeiro (Barra da Tijuca)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"493",  nome:"Rio de Janeiro (Campo Grande)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"495",  nome:"Rio de Janeiro (Del Castilho)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1740", nome:"Rio de Janeiro (Ilha do Governador - Tauá)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"462",  nome:"Rio de Janeiro (Madureira)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1843", nome:"Rio de Janeiro (Museu do Amanhã)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1833", nome:"Rio de Janeiro (Santa Cruz)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1957", nome:"Rio de Janeiro (Santíssimo)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1983", nome:"Rio de Janeiro (Taquara)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1937", nome:"Rio de Janeiro (Tijuca)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"1992", nome:"Rio de Janeiro (Vila da Penha)", cidade:"Rio de Janeiro", estado:"RJ" },
  { codigo:"551",  nome:"São Gonçalo (Alcântara)", cidade:"São Gonçalo", estado:"RJ" },
  { codigo:"1973", nome:"São João de Meriti (Vilar dos Teles)", cidade:"São João de Meriti", estado:"RJ" },
  { codigo:"180",  nome:"Três Rios (Centro)", cidade:"Três Rios", estado:"RJ" },
  { codigo:"181",  nome:"Valença (Centro)", cidade:"Valença", estado:"RJ" },
  { codigo:"263",  nome:"Natal (Cidade Alta)", cidade:"Natal", estado:"RN" },
  { codigo:"1904", nome:"Parnamirim (Centro)", cidade:"Parnamirim", estado:"RN" },
  { codigo:"1967", nome:"Alto Paraíso (Centro)", cidade:"Alto Paraíso", estado:"RO" },
  { codigo:"321",  nome:"Ariquemes (Setor 01)", cidade:"Ariquemes", estado:"RO" },
  { codigo:"379",  nome:"Ariquemes (Setor Institucional)", cidade:"Ariquemes", estado:"RO" },
  { codigo:"371",  nome:"Ouro Preto do Oeste (Jardim bandeirantes)", cidade:"Ouro Preto do Oeste", estado:"RO" },
  { codigo:"369",  nome:"Guajará-Mirim (ST. 03)", cidade:"Guajará-Mirim", estado:"RR" },
  { codigo:"1598", nome:"Alegrete (Centro)", cidade:"Alegrete", estado:"RS" },
  { codigo:"1910", nome:"Bagé (Centro)", cidade:"Bagé", estado:"RS" },
  { codigo:"1625", nome:"Bom Retiro do Sul (Centro)", cidade:"Bom Retiro do Sul", estado:"RS" },
  { codigo:"43",   nome:"Cachoeira do Sul (Rio Branco)", cidade:"Cachoeira do Sul", estado:"RS" },
  { codigo:"1959", nome:"Cachoeirinha (Vila Cachoeirinha)", cidade:"Cachoeirinha", estado:"RS" },
  { codigo:"1929", nome:"Camaquã (Centro)", cidade:"Camaquã", estado:"RS" },
  { codigo:"110",  nome:"Canoas (Mathias Velho)", cidade:"Canoas", estado:"RS" },
  { codigo:"211",  nome:"Ivoti (Concórdia)", cidade:"Ivoti", estado:"RS" },
  { codigo:"196",  nome:"Novo Hamburgo (Centro)", cidade:"Novo Hamburgo", estado:"RS" },
  { codigo:"1960", nome:"Porto Alegre (Centro Histórico)", cidade:"Porto Alegre", estado:"RS" },
  { codigo:"73",   nome:"Porto Alegre (Santa Maria Goretti)", cidade:"Porto Alegre", estado:"RS" },
  { codigo:"1934", nome:"Quaraí (Centro)", cidade:"Quaraí", estado:"RS" },
  { codigo:"51",   nome:"Rio Grande (Centro)", cidade:"Rio Grande", estado:"RS" },
  { codigo:"291",  nome:"Santana do Livramento (Hidráulica)", cidade:"Santana do Livramento", estado:"RS" },
  { codigo:"302",  nome:"Santo Antônio da Patrulha (Cidade Alta)", cidade:"Santo Antônio da Patrulha", estado:"RS" },
  { codigo:"1860", nome:"SANDRA ALTAIDE FERERIA TIYODA", cidade:"", estado:"" },
  { codigo:"1808", nome:"SANTOS E SANTOS - SERVICOS EMPRESARIAIS E", cidade:"", estado:"" },
  { codigo:"93",   nome:"Balneário Camboriú (Centro)", cidade:"Balneário Camboriú", estado:"SC" },
  { codigo:"156",  nome:"Blumenau (Bom Retiro)", cidade:"Blumenau", estado:"SC" },
  { codigo:"323",  nome:"Criciúma (Comerciário)", cidade:"Criciúma", estado:"SC" },
  { codigo:"1998", nome:"Florianópolis (Centro)", cidade:"Florianópolis", estado:"SC" },
  { codigo:"475",  nome:"Frei Rogério (Distrito Núcleo Triticícola)", cidade:"Frei Rogério", estado:"SC" },
  { codigo:"407",  nome:"Iporã do Oeste (Centro)", cidade:"Iporã do Oeste", estado:"SC" },
  { codigo:"119",  nome:"Itajaí (Murta)", cidade:"Itajaí", estado:"SC" },
  { codigo:"113",  nome:"Itapoá (Itapema do Norte)", cidade:"Itapoá", estado:"SC" },
  { codigo:"88",   nome:"Jaraguá do Sul (Centro)", cidade:"Jaraguá do Sul", estado:"SC" },
  { codigo:"84",   nome:"Joinville (Centro)", cidade:"Joinville", estado:"SC" },
  { codigo:"458",  nome:"Joinville (Petrópolis)", cidade:"Joinville", estado:"SC" },
  { codigo:"1770", nome:"Lages (Centro)", cidade:"Lages", estado:"SC" },
  { codigo:"1696", nome:"Lages (Copacabana)", cidade:"Lages", estado:"SC" },
  { codigo:"90",   nome:"Navegantes (São Pedro)", cidade:"Navegantes", estado:"SC" },
  { codigo:"1771", nome:"Palhoça (Bela Vista)", cidade:"Palhoça", estado:"SC" },
  { codigo:"1924", nome:"SISTEMA INTEGRADO DE EDUCAÇÃO BÁSICA E PR", cidade:"", estado:"" },
  { codigo:"1965", nome:"ARAÇATUBA (CENTRO)", cidade:"Araçatuba", estado:"SP" },
  { codigo:"210",  nome:"Americana (Centro)", cidade:"Americana", estado:"SP" },
  { codigo:"1927", nome:"Araraquara (Centro)", cidade:"Araraquara", estado:"SP" },
  { codigo:"546",  nome:"Barueri (Jardim Itaparica)", cidade:"Barueri", estado:"SP" },
  { codigo:"375",  nome:"Bauru (Vila Universitária)", cidade:"Bauru", estado:"SP" },
  { codigo:"1685", nome:"Boituva (Centro)", cidade:"Boituva", estado:"SP" },
  { codigo:"450",  nome:"Botucatu (Centro)", cidade:"Botucatu", estado:"SP" },
  { codigo:"1757", nome:"COSMÓPOLIS (JARDIM BELA VISTA)", cidade:"Cosmópolis", estado:"SP" },
  { codigo:"1963", nome:"Campinas (Centro)", cidade:"Campinas", estado:"SP" },
  { codigo:"1732", nome:"Campinas (Jardim Novo Campos Elíseos)", cidade:"Campinas", estado:"SP" },
  { codigo:"1899", nome:"Carapicuíba (Vila Dirce)", cidade:"Carapicuíba", estado:"SP" },
  { codigo:"1687", nome:"Cotia (centro Vila Monte Serrat)", cidade:"Cotia", estado:"SP" },
  { codigo:"1976", nome:"Diadema (Centro)", cidade:"Diadema", estado:"SP" },
  { codigo:"1898", nome:"Embu-Guaçu (Centro)", cidade:"Embu-Guaçu", estado:"SP" },
  { codigo:"461",  nome:"Fernandópolis (Centro)", cidade:"Fernandópolis", estado:"SP" },
  { codigo:"1749", nome:"Franca (Centro)", cidade:"Franca", estado:"SP" },
  { codigo:"1943", nome:"Franco da Rocha (Vila Zanela)", cidade:"Franco da Rocha", estado:"SP" },
  { codigo:"228",  nome:"Guarujá (Vila Alice Vicente de Carvalho)", cidade:"Guarujá", estado:"SP" },
  { codigo:"1936", nome:"Guarulhos (Centro)", cidade:"Guarulhos", estado:"SP" },
  { codigo:"229",  nome:"Guarulhos - Profaci (Jardim Toscana)", cidade:"Guarulhos", estado:"SP" },
  { codigo:"21",   nome:"Itanhaém (Jd Sabauna)", cidade:"Itanhaém", estado:"SP" },
  { codigo:"318",  nome:"Itapecerica da Serra (Centro)", cidade:"Itapecerica da Serra", estado:"SP" },
  { codigo:"422",  nome:"Itapetininga (Centro - Doutor Virgílio)", cidade:"Itapetininga", estado:"SP" },
  { codigo:"1826", nome:"Itapetininga (Centro)", cidade:"Itapetininga", estado:"SP" },
  { codigo:"1673", nome:"Japão (Aichi)", cidade:"Aichi", estado:"JP" },
  { codigo:"1621", nome:"Leme (Barra Funda)", cidade:"Leme", estado:"SP" },
  { codigo:"1656", nome:"Limeira (CENTRO ACIMA)", cidade:"Limeira", estado:"SP" },
  { codigo:"193",  nome:"Mogi Guaçu (Jardim Novo II)", cidade:"Mogi Guaçu", estado:"SP" },
  { codigo:"1699", nome:"Mogi Mirim (Nova Mogi)", cidade:"Mogi Mirim", estado:"SP" },
  { codigo:"204",  nome:"Orlândia (Centro)", cidade:"Orlândia", estado:"SP" },
  { codigo:"1776", nome:"Osasco (APOS)", cidade:"Osasco", estado:"SP" },
  { codigo:"79",   nome:"Osasco (Centro - Rua Ruy Barbosa)", cidade:"Osasco", estado:"SP" },
  { codigo:"1756", nome:"Osasco (Centro)", cidade:"Osasco", estado:"SP" },
  { codigo:"1915", nome:"Piracicaba (Centro)", cidade:"Piracicaba", estado:"SP" },
  { codigo:"1946", nome:"Praia Grande (Mirim)", cidade:"Praia Grande", estado:"SP" },
  { codigo:"1747", nome:"Presidente Prudente (Jardim Paulista)", cidade:"Presidente Prudente", estado:"SP" },
  { codigo:"1654", nome:"Ribeirão Preto (Centro)", cidade:"Ribeirão Preto", estado:"SP" },
  { codigo:"68",   nome:"Ribeirão Preto (Parque dos Bandeirantes)", cidade:"Ribeirão Preto", estado:"SP" },
  { codigo:"1773", nome:"Ribeirão Preto (Vila Seixas)", cidade:"Ribeirão Preto", estado:"SP" },
  { codigo:"80",   nome:"Rio Claro (Centro)", cidade:"Rio Claro", estado:"SP" },
  { codigo:"1729", nome:"Santo André (Jardim)", cidade:"Santo André", estado:"SP" },
  { codigo:"223",  nome:"Santos (Gonzaga)", cidade:"Santos", estado:"SP" },
  { codigo:"1942", nome:"Sorocaba (Centro)", cidade:"Sorocaba", estado:"SP" },
  { codigo:"1658", nome:"Suzano (Centro)", cidade:"Suzano", estado:"SP" },
  { codigo:"1863", nome:"São Bernardo do Campo (Centro)", cidade:"São Bernardo do Campo", estado:"SP" },
  { codigo:"1993", nome:"São Bernardo do Campo (Rudge Ramos)", cidade:"São Bernardo do Campo", estado:"SP" },
  { codigo:"1746", nome:"São Caetano do Sul (Centro)", cidade:"São Caetano do Sul", estado:"SP" },
  { codigo:"64",   nome:"São Carlos (Vila Monteiro Gleba I)", cidade:"São Carlos", estado:"SP" },
  { codigo:"1750", nome:"São Joaquim da Barra (Centro)", cidade:"São Joaquim da Barra", estado:"SP" },
  { codigo:"1825", nome:"São José do Rio Preto (Vila Santa Cruz)", cidade:"São José do Rio Preto", estado:"SP" },
  { codigo:"1691", nome:"São José dos Campos (Jardim São Dimas)", cidade:"São José dos Campos", estado:"SP" },
  { codigo:"1933", nome:"São Paulo (Butantã)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1838", nome:"São Paulo (CENTRO)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1713", nome:"São Paulo (Campo Limpo / Vila Pirajussara)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1972", nome:"São Paulo (Capão Redondo)", cidade:"São Paulo", estado:"SP" },
  { codigo:"393",  nome:"São Paulo (Cidade Monções)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1862", nome:"São Paulo (Cidade São Mateus)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1970", nome:"São Paulo (Itaim Paulista)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1834", nome:"São Paulo (Itaquera)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1974", nome:"São Paulo (Itaquera 2)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1897", nome:"São Paulo (Jabaquara)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1653", nome:"São Paulo (Lapa)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1956", nome:"São Paulo (Santo Amaro)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1850", nome:"São Paulo (Tatuapé)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1733", nome:"São Paulo (Vila Nova Cachoeirinha)", cidade:"São Paulo", estado:"SP" },
  { codigo:"1884", nome:"São Vicente (Centro)", cidade:"São Vicente", estado:"SP" },
  { codigo:"3",    nome:"Taboão da Serra (Jardim Maria Rosa)", cidade:"Taboão da Serra", estado:"SP" },
  { codigo:"1953", nome:"Tatuí (Centro)", cidade:"Tatuí", estado:"SP" },
  { codigo:"1716", nome:"Tietê (Centro)", cidade:"Tietê", estado:"SP" },
  { codigo:"197",  nome:"Ubatuba (Umuarama)", cidade:"Ubatuba", estado:"SP" },
  { codigo:"1626", nome:"TABATA DA SILVA SANTOS", cidade:"", estado:"" },
  { codigo:"1611", nome:"THIAGO DA SILVA SIQUEIRA", cidade:"", estado:"" },
  { codigo:"1950", nome:"Araguatins (Centro)", cidade:"Araguatins", estado:"TO" },
  { codigo:"1661", nome:"Gurupi (Setor Central)", cidade:"Gurupi", estado:"TO" },
  { codigo:"1591", nome:"TVJ Educacional LTDA", cidade:"", estado:"" },
  { codigo:"1810", nome:"VIVER EM MOVIMENTO SOLUCOES EM DESENVOLVI", cidade:"", estado:"" },
  { codigo:"1912", nome:"WMK ESCOLA TECNICA DE ENFERMAGEM LTDA", cidade:"", estado:"" },
  { codigo:"1636", nome:"WS Ensino de Idiomas Eireli", cidade:"", estado:"" },
];

export function searchPolos(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return POLOS_SISTEMA.filter(p =>
    p.nome.toLowerCase().includes(q) ||
    p.codigo.includes(q) ||
    p.cidade.toLowerCase().includes(q) ||
    p.estado.toLowerCase().includes(q)
  ).slice(0, 10);
}
